/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sorter_Sorter */

#ifndef _Included_Sorter_Sorter
#define _Included_Sorter_Sorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sorter_Sorter
 * Method:    SortC
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_Sorter_Sorter_SortC
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
